import styles from "./styles/layout.module.css"
import Footer from "./componentes/Footer"
import Menu from "./componentes/Menu"
import Image from "next/image"

import Head from 'next/head'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div className={styles.container}>
      <Menu />
        <main className={styles.content}>
          {children}
        </main>
        <footer className={styles.footer}>
          <Footer />
        </footer>
    </div>

    /*<>
    <Menu />
       <main className="main-container">{children}</main>
    <Footer />   
    </>*/   
  )
}
